server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiktok?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
mybatis:
  # 配置MyBatis的全局属性
  configuration:
    cacheEnabled: false # 关闭缓存
    mapUnderscoreToCamelCase: true # 开启驼峰命名法转换
